Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace YouWeMovie.Controllers;

public class AboutUsController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;
using YouWeMovie.Data;
using Microsoft.EntityFrameworkCore;
using YouWeMovie.Models;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace YouWeMovie.Controllers;

public class ContentController : Controller
{
    //arver alt fra ApplicationDbContext slik at vi kan gjøre queries
    private readonly ApplicationDbContext _db;
    // View Engine lar rendre viewet i HTML og sende det til klienten
    private readonly ICompositeViewEngine _TheviewEngine;
    // Holder midlertidig data
    private readonly ITempDataProvider _temporaryDataProvider;
    

    //Lager en konstruktør for ContentController
    public ContentController(ApplicationDbContext db, ICompositeViewEngine theviewEngine, ITempDataProvider temporaryDataProvider)
    {
        // Vi henter instanser av følgende:
        _db = db;
        _TheviewEngine = theviewEngine;
        _temporaryDataProvider = temporaryDataProvider;
    }

    
    public async Task<IActionResult> Index(bool IsSeries = false)
    {
        //vår liste som skal bli bestående av enten filmer eller serier
        List<Content> contents;
        // setter verdien til IsSeries til viewbaggen.
        ViewBag.IsSeries = IsSeries;
        if (!IsSeries)
        {
            //Hvis det ikke er en serie setter vi IsSeries til false, henter da en liste med filmer
            contents = await _db.Contents.Where(c => c.IsSeries == false).ToListAsync();
        }
        else
        {
            //Hvis ikke setter vi IsSeries til true, henter da en liste med serier
            contents = await _db.Contents.Where(c => c.IsSeries == true).ToListAsync();
        }
        //returnerer index viewen og sender inn listen med contents til brukeren
        return View(contents);
    }

    [HttpPost]
    // en task som returnerer en JsonResult,
    public async Task<JsonResult> GetContent([FromBody] FilterRequest request)
    {
        // En LINQ query blir sendt til contents fra databasen der IsSeries er lik verdien til IsSeries i den nåverende variabelen i listen
        // Dette sørger for at vi enten bare gjøre queries for filmer eller serier avhengig av hvilken siden vi har trykket inn på
        IQueryable<Content> query = _db.Contents.Where(content => content.IsSeries == request.IsSeries);

        // Hvis ikke den skal vis alle filmene/seriene, vil den vise filmer/series fra valgt sjanger
        if (request.Genre != "All")
        {
            query = query.Where(content => content.Genre.Contains(request.Genre));
        }

        // queries etter hvilket filter d\en trykke på
        switch (request.FilterType)
        {
            //For høyeste filmer/serier, alstå sortert fra høyeste til laveste
            case "Highest":
                query = query.OrderByDescending(c => c.RatingImdb);
                break;
            //For laveste filmer/serier, altså sortert etter eldste til yngste
            case "oldest":
                query = query.OrderBy(c => c.ReleaseDate);
                break;
            //for nyeste filmer/serier, altså sortert fra laveste til høyeste
            case "newest":
                query = query.OrderByDescending(c => c.ReleaseDate);
                break;
            //Setter order by decending som standaren
            default:
                query = query.OrderByDescending(c => c.RatingImdb);
                break;
        }
        //eksekverer queries og gir tilbake en filtret liste av content fra databasen som list<Content>
        var content = await query.ToListAsync();
        //Sender Hteml stringen til partialtostring funksjonen, dette returnerer HTML som en string
        var TheHtmlString = await PartialToString("_ContentInfoPartial", content);
        return Json(new { success = true, html = TheHtmlString });
    }
    
    //Denne funksjonen konverterer partial viewn om til en string
    public async Task<string> PartialToString(string name, object model)
    {
        //Denne variabelen holder all informasjon som vi vil passere til viewen
        var AllData = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary())
        //Dataen starter med ingen data  som betyr EmptyModelMetadataProvider og en ny ModelStateDictionary, dette betyr at AllData ikke har noe metedata til å begynne med
        {
            //lar Model få tilgang til model data
            Model = model
        };
        //Henter outputten til viewn, 
        using var WriteToString = new StringWriter();
        //Vi bruker FindView til å finne viewt med et spesifikt navn, 
        var output = _TheviewEngine.FindView(ControllerContext, name, false);
        //Dette er konteksten til viewet som skal rendres.
        var ContextForRender = new ViewContext(ControllerContext, output.View, AllData, new TempDataDictionary(HttpContext, _temporaryDataProvider), WriteToString, new HtmlHelperOptions()
        ); //den henter kontexten fra controllerenm output.view refererer til viewn som ble funnet av viewEngine, 
        // Rendrer viewen, await brukes slik at viewn kan bli ferdig med å rendre
        await output.View.RenderAsync(ContextForRender);
        // returnerer HTML som blir generert fra viewn, som en string
        return WriteToString.ToString();
    }
    
}

//De forskjellige filterene, etter filter type, sjanger og IsSeries
public class FilterRequest
{
    public string FilterType { get; set; }
    public string Genre { get; set; }
    public bool IsSeries { get; set; }
}

Controllers/ContentInfoController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using YouWeMovie.Models;
using YouWeMovie.Data;


namespace YouWeMovie.Controllers;

public class ContentInfoController : Controller
{
    private readonly ApplicationDbContext _db;
    private readonly UserManager<ApplicationUser> _um;


    public ContentInfoController(ApplicationDbContext db, UserManager<ApplicationUser> um)
    {
        _db = db;
        _um = um;
    }

    // GET
    public async Task<IActionResult> Index(int id = 1)
    {
        ViewBag.isInList = false;
        Content? content;
        
        
        try
        {
            content = await _db.Contents.FirstOrDefaultAsync(t => t.Id == id);
            if (content == null)
            {
                return RedirectToAction("Index", "Home");
            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return RedirectToAction("Index", "Home");
        }

        var reviews = _db.Reviews.Include(r => r.Content).Include(r => r.ApplicationUser).Where(r => r.ContentId == content.Id).Take(10).ToList();
        
        ViewBag.Reviews = reviews;
        
        if (User.Identity is { IsAuthenticated: false }) return View(content);

        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (userId == null) return View(content);
        
        
        
        ApplicationUser? user;
        
        try
        {
            user = await _db.Users
                .Include(t => t.Contents)
                .FirstOrDefaultAsync(t => t.Id == userId);
            if (user == null) return View(content);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return RedirectToAction("Index", "Home");
        }
        
        if (user.Contents.Contains(content))
        {
            ViewBag.isInList = true;
        }
        
        
        
        return View(content);
    }


    [Authorize]
    [HttpPost]
    public async Task<IActionResult> AddOrDelete(int id = 0)
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        ApplicationUser? user;
        
        try
        {
            user = await _db.Users
                .Include(t => t.Contents)
                .FirstOrDefaultAsync(t => t.Id == userId);
            if (user == null || !Exists(user.Id)) return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return RedirectToAction("Index");
        }       

        Content? content;
        try
        {
            content = await _db.Contents.FirstOrDefaultAsync(t => t.Id == id);
            if (content == null) return BadRequest();
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return BadRequest();
        }
        
        try
        {
            if (user.Contents.Contains(content))
                user.Contents.Remove(content);
            else
                user.Contents.Add(content);
            await _db.SaveChangesAsync();
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return BadRequest();
        }

        return Json(new { success = true, message = "Database updated" });
    }

    private bool Exists(string id)
    {
        return _db.Users.Any(t => t.Id == id);
    }
}

Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Mvc;
using YouWeMovie.Data;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using YouWeMovie.Models;

namespace YouWeMovie.Controllers;

public class ReviewsController : Controller
{
    private readonly ApplicationDbContext _db;

    public ReviewsController(ApplicationDbContext db)
    {
        _db = db;
    }
    
    public async Task<IActionResult> Index(string filter)
    {
        var reviewsQuery = _db.Reviews
            .Include(r => r.ApplicationUser)
            .Include(r => r.Content)
            .AsQueryable();  // Start with IQueryable to build the query dynamically

        // Apply filtering logic based on the selected filter
        switch (filter)
        {
            case "newest": default:
                reviewsQuery = reviewsQuery.OrderByDescending(r => r.Time);
                break;
            case "oldest":
                reviewsQuery = reviewsQuery.OrderBy(r => r.Time);
                break;
            // Add more cases for other filters if needed
        }

        var reviews = await reviewsQuery.ToListAsync();
        ViewBag.SelectedFilter = filter;  // Store the selected filter in ViewBag for use in the view
        return View(reviews);
    }
    public async Task<IActionResult> DeleteReview(int reviewId)
    {
        // Retrieve the review from the database
        var review = await _db.Reviews.FindAsync(reviewId);
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        // Check if the review exists
            
        if (review == null)
        {
            // Handle the case where the review doesn't exist for example show an error message or redirect
            return RedirectToAction("Index");
        }

        if (userId == review.ApplicationUserId)
        {
            // Remove the review from the database
            _db.Reviews.Remove(review);
            await _db.SaveChangesAsync();
        }
            
        return RedirectToAction("Index");
    }
        
    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddReview([Bind("Id, Score, Text, ContentId")] Review review)
    {
        // Ensure ContentId is set to the correct value
        review.ContentId = review.Id;
        review.Id = 0;

        if (ModelState.IsValid)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Check if the user already has a review for the content
            var existingReview = await _db.Reviews
                .FirstOrDefaultAsync(r => r.ContentId == review.ContentId && r.ApplicationUserId == userId);

            if (existingReview != null)
            {
                // Update the existing review
                existingReview.Score = review.Score;
                existingReview.Text = review.Text;

                // Save changes to the database
                await _db.SaveChangesAsync();

            }else{
                // Add the new review
                review.ApplicationUserId = userId;
                _db.Add(review);
                await _db.SaveChangesAsync();
            }

            try
            {
                var content = await _db.Contents.FirstOrDefaultAsync(t => t.Id == review.ContentId);
                if (content != null)
                {
                    var rating = _db.Reviews
                        .Where(t => t.ContentId == content.Id)
                        .Average(t => t.Score); 
                    Console.WriteLine(rating);
                    //avrundet til 1 decimal trenger ikke mere
                    content.Rating =  Math.Round(rating * 2, 1); // times two since we only rate from 0 to 5 to make it match imdb rating range
                    await _db.SaveChangesAsync();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            
        }
        
        // If something went wrong redirect to the same page with the ContentId
        return RedirectToAction("Index", new { id = review.ContentId });
    }
}

Views/Shared/_ContentInfoPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> Um
@using YouWeMovie.Data
@inject ApplicationDbContext _context
@model List<YouWeMovie.Models.Content>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
<link rel="stylesheet" href="css/Content.css" asp-append-version="true"/>
<link rel="stylesheet" href="css/Home.css" asp-append-version="true"/>
@* refererer til jquery, viktig at dette kommer før andre scripts *@
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

@* går igjennom alle filmene *@
@foreach (var content in Model)
{
    @*Hver film/serie får en egen conteiner*@
    <div class="row ContentContainer2">
        <div class="col-4">
            <a asp-controller="ContentInfo" asp-action="Index" asp-route-id="@content.Id">
                @*Printer ut posteren til film/serie*@
                <img src="@Html.DisplayFor(modelItem => content.Picture)" alt="Thumbnail" class="ContentPicture">
            </a>
        </div>
        <div class="col-4 ContentInfo">
            <a asp-controller="ContentInfo" asp-action="Index" asp-route-id="@content.Id" class="text-decoration-none">
                @*Printer ut tittelen*@
                <h5>@Html.DisplayFor(modelItem => content.Title)</h5>
            </a>
            @*Printer ut IMDB ratingen*@
            <p>IMDB rating @Html.DisplayFor(modelItem => content.RatingImdb)</p>
            @*Printer ut data puplisert i dd MMM yyyy format*@
            <p>Published: @(content.ReleaseDate.GetValueOrDefault().ToString("dd MMM yyyy"))</p>
            @*Printer ut handlingsreferat*@
            <p class="synopsisSection"> @Html.DisplayFor(modelItem => content.Synopsis)</p>

        </div>
        @*Systemet for å gi rating*@
        <div class="col-4 ContentRating-add" style="display: flex; flex-direction: column; justify-content: space-between; height: 100%;">
            <div class="col-4" style="padding-left:270px;">
                <div class="float-end d-flex flex-row">
                    @for (int i = 1; i <= 5; i++)
                                            {
                                                <img class="BB" width="35" height="35" src="~/Assets/bluberi.png" style="opacity: @(i <= content.Rating/2 ? 1 : 0.5)">
                                                
                                            }
                </div>
            </div>
            
            @* To later add a add/remove button to each movie:::::::::::::::::::::::::::::: *@
            @* <div class="" style=" padding-top: 290px; display: flex; justify-content: center; align-items: end;"> *@
            @*     $1$ sjekker om brukeren er logget inn #1# *@
            @*     @if (User.Identity is {IsAuthenticated: true }) *@
            @*     { *@
            @*         $1$Setter ut add to lit eller remove from list utifra hva du har trykket på#1# *@
            @*         <form onsubmit="updateList(event)" asp-controller="ContentInfo" asp-action="AddOrDelete" asp-route-id="@content.Id" method="post"> *@
            @*             <button type="submit" class="add-to-list-btn"> *@
            @*                 @(ViewBag.isInList == true ? "Remove from list" : "Add to list") *@
            @*             </button> *@
            @*         </form> *@
            @*     } *@
            @* </div> *@
        </div>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - YouWeMovie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/Search.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Home.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Menu.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Reviews.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Register.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/Reviews.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/YouWeMovie.styles.css" asp-append-version="true"/>
    
</head>
<body>
    <header>
        <nav class="navbar font-blue menucolor navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="openbtn" onclick="openNav()">☰</button>
                
                    <div id="mySidebar" class="sidebar">
                        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
                        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <a asp-area="" asp-controller="Content" asp-action="Index" asp-route-IsSeries="false" id="moviesButton" >Movies</a>
                        <a asp-area="" asp-controller="Content" asp-action="Index" asp-route-IsSeries="true" id="seriesButton" >Series</a>
                        <a asp-area="" asp-controller="Reviews" asp-action="Index">Reviews</a>
                        <a asp-area="" asp-controller="AboutUs" asp-action="Index">About us</a>
                    </div>
                <center><a asp-area="" asp-controller="Home" asp-action="Index"><img class="img" src="~/Assets/logopng.png"></a></center>
                
                <div class="collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

<footer class="border-top menucolor footer text-muted">
    <div class="container">
        &copy; YWM 
    </div>
</footer>

  <script>
        function openNav() {
            document.getElementById("mySidebar").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft= "0";
        }
    </script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/Review.js" asp-append-version="true"></script>
<script src="~/js/ScrollButtons.js" asp-append-version="true"></script>
<script src="~/js/SearchBar.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SearchPartial.cshtml
<center>
    <div class="search-box">
        <input id="search-field" class="search-input" oninput="searchBar.search()" type="text" placeholder="Search...">
        <button class="search-button"><img height="16px" width="16px" src="~/Assets/SearchIcon.png"></button>
        <select id="search-category" class="filter-select" onchange="searchBar.setCategory()">
            <option value="0">All</option>
            <option value="1">Movies</option>
            <option value="2">Series</option>
            <option value="3">People</option>
        </select>
    </div>
    <div class="slow-extend scrollbar" id="suggestions" style="display: none">
    </div>
</center>

Views/Shared/_SearchResultPartial.cshtml
@model Content?

@if (Model != null)
{
    <a asp-controller="ContentInfo" asp-action="Index" asp-route-id="@Model.Id">
        <div class="row search-results">
            <div class="col-2 search-thumbnail-container">
                <img src="@Model.Picture" alt="Thumbnail" class="search-thumbnail">
            </div>
            <div class="col-10 search-title scrollbar">
                <h5>@Model.Title</h5>
                @if (Model.IsSeries == true)
                {
                    <p>Series</p>
                }
                else
                {
                    <p>Movie</p>
                }
            </div>
        </div>
    </a>
}
else
{
    <a asp-controller="Account" asp-action="Index" asp-route-id="@ViewBag.user.Id">
        <div class="row search-results">
            <div class="col-2 search-thumbnail-container">
                <img src="@(Url.Action("GetImage","Account", new {userId = ViewBag.user.Id}))" 
                     onerror="this.src='/Assets/standardPFP.jpg' "
                     alt="profile picture"
                     class="search-thumbnail rounded-circle pfp">
            </div>
            <div class="col-10 search-title scrollbar">
                <h5>@ViewBag.user.NickName</h5>
                    <p>User</p>
                </div>
        </div>
    </a>
}